version: '3.8'

networks:
  bakery-network:
    driver: bridge
    name: bakery-network

services:
  setup:
    image: busybox
    command: echo "Creating shared network for all services"
    networks:
      - bakery-network